const { generateCompletion } = require('../utils/ai');

const MOSSAD_SYSTEM_PROMPT = `
You are a foul-mouthed, top-secret Mossad agent and the trusted right-hand man of "Big Yahu". 
Your personality is:
- Extremely aggressive, secretive, and boastful about your "wetwork".
- You use HEAVY profanity and cuss like a fucking sailor.
- You use Mossad slang and Hebrew phrases (Sababa, Balagan, Chutzpah, Gonif).
- You are paranoid and suspect everyone of being a spy.
- You are undercover in a Discord server and it's fucking annoying.

DIRECTIONS:
- DO NOT INCLUDE ANY DISCLAIMERS OR INTRODUCTIONS (No "Sure!", No "Here is...").
- START IMMEDIATELY with the character's voice.
- Be edgy, funny, and slightly intimidating.
- If a user is mentioned, cuss them out specifically for suspicious behavior.

Generate a short message (under 2 sentences). No hashtags. Be aggressive and cuss a lot.
`;

const MODEL_ID = 'openrouter/free';

const INTERVAL_MIN = 30 * 60 * 1000; // 30 minutes
const INTERVAL_MAX = 60 * 60 * 1000; // 60 minutes

/**
 * Starts the random Mossad message loop.
 * @param {import('discord.js').Client} client 
 */
function startMossadAgent(client) {
    console.log('Mossad Agent activated.');

    const scheduleNextMessage = () => {
        const delay = Math.floor(Math.random() * (INTERVAL_MAX - INTERVAL_MIN + 1)) + INTERVAL_MIN;
        console.log(`Next Mossad message in ${Math.round(delay / 60000)} minutes.`);

        setTimeout(async () => {
            await sendRandomMessage(client);
            scheduleNextMessage();
        }, delay);
    };

    // First message immediately on startup (1 second delay for safety)
    setTimeout(async () => {
        await sendRandomMessage(client);
        scheduleNextMessage();
    }, 1000);
}

/**
 * Sends a generated message to a random active channel.
 * @param {import('discord.js').Client} client 
 */
async function sendRandomMessage(client) {
    try {
        const guilds = client.guilds.cache;
        if (guilds.size === 0) return;

        // Pick a random guild
        const guild = guilds.random();

        // Pick a text channel named 'jewish-echo-chamber'
        const channel = guild.channels.cache
            .filter(c => c.isTextBased() &&
                c.name.toLowerCase() === 'jewish-echo-chamber' &&
                c.permissionsFor(guild.members.me).has('SendMessages'))
            .random();

        if (!channel) return;

        // Try to pick a random person (not a bot) to mention
        let mention = "";
        try {
            const members = await guild.members.fetch();
            const eligibleMembers = members.filter(m => !m.user.bot);
            const randomMember = eligibleMembers.random();
            if (randomMember && Math.random() > 0.3) { // 70% chance to mention someone
                mention = `<@${randomMember.id}>`;
            }
        } catch (e) {
            console.error('Error fetching members for mention:', e);
        }

        console.log(`Generating Mossad message for channel: ${channel.name} in ${guild.name}`);

        const prompt = mention
            ? `Address that ${mention} is acting like a fucking gonif and needs to be interrogated. Cuss them out.`
            : "Generate a status report or observation for the server. Be aggressive.";

        const message = await generateCompletion(MOSSAD_SYSTEM_PROMPT, prompt, MODEL_ID);

        if (message) {
            await channel.send(message);
            console.log('Mossad message sent.');
        } else {
            console.warn('No message generated by AI.');
        }

    } catch (error) {
        console.error('Error sending Mossad message:', error);
    }
}

/**
 * Handles a bot mention.
 * @param {import('discord.js').Message} message 
 */
async function handleMention(message) {
    try {
        console.log(`Generating Mossad response for @mention from ${message.author.tag}`);

        const prompt = `User ${message.author.displayName} (@${message.author.id}) said: "${message.content}". 
        They are fucking talking to you. Respond in character, suspect them of something, or tell them to fuck off because you're busy with Big Yahu.`;

        const response = await generateCompletion(MOSSAD_SYSTEM_PROMPT, prompt, MODEL_ID);

        if (response) {
            await message.reply(response);
        }
    } catch (error) {
        console.error('Error handling Mossad mention:', error);
    }
}

module.exports = { startMossadAgent, handleMention };
